//Only for development – using temporary dummy data instead of API

export default function dummydata() {
  return {
    results: [
      {
        id: 1,
        title: "Amaretto espresso martini",
        preptime: "7mins",
        rating: "5 stars",
        image: "/dummydata/download.jpeg",
        imageType: "jpeg",
      },
      {
        id: 2,
        title: "Aperol Spritz",
        preptime: "7mins",
        rating: "5 stars",
        image: "/dummydata/download.jpeg",
        imageType: "jpeg",
      },
      {
        id: 3,
        title: "Cosmopolitan",
        preptime: "7mins",
        rating: "5 stars",
        image: "/dummydata/download.jpeg",
        imageType: "jpeg",
      },
      {
        id: 4,
        title: "Sangria",
        preptime: "7mins",
        rating: "5 stars",
        image: "/dummydata/download.jpeg",
        imageType: "jpeg",
      },
      {
        id: 5,
        title: "Banana daiquiri",
        preptime: "7mins",
        rating: "5 stars",
        image: "/dummydata/download.jpeg",
        imageType: "jpeg",
      },
      {
        id: 6,
        title: "Rhubarb fizz",
        preptime: "7mins",
        rating: "5 stars",
        image: "/dummydata/download.jpeg",
        imageType: "jpeg",
      },
      {
        id: 7,
        title: "Hugo",
        preptime: "7mins",
        rating: "5 stars",
        image: "/dummydata/download.jpeg",
        imageType: "jpeg",
      },
      {
        id: 8,
        title: "Margarita",
        preptime: "7mins",
        rating: "5 stars",
        image: "/dummydata/download.jpeg",
        imageType: "jpeg",
      },
      {
        id: 9,
        title: "Black russian cocktail",
        preptime: "7mins",
        rating: "5 stars",
        image: "/dummydata/download.jpeg",
        imageType: "jpeg",
      },
      {
        id: 10,
        title: "Sex on the beach",
        preptime: "7mins",
        rating: "5 stars",
        image: "/dummydata/download.jpeg",
        imageType: "jpeg",
      },
      {
        id: 11,
        title: "Cuba libre",
        preptime: "7mins",
        rating: "5 stars",
        image: "/dummydata/download.jpeg",
        imageType: "jpeg",
      },
      {
        id: 12,
        title: "Mojito",
        preptime: "7mins",
        rating: "5 stars",
        image: "/dummydata/download.jpeg",
        imageType: "jpeg",
      },
    ],
  };
}
