//Only for development – using temporary dummy data instead of API

export default function dummydata() {
  return {
    results: [
      {
        id: 1,
        title: "Pasta With Tuna",
        preptime: "1h 25min",
        rating: "5 stars",
        image: "/dummydata/654959-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 2,
        title: "Pasta Margherita",
        preptime: "1h 25min",
        rating: "5 stars",
        image: "/dummydata/511728-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 3,
        title: "Pasta On The Border",
        preptime: "1h 25min",
        rating: "5 stars",
        image: "/dummydata/654857-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 4,
        title: "Pasta With Tuna",
        preptime: "1h 25min",
        rating: "5 stars",
        image: "/dummydata/654959-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 5,
        title: "Pasta Margherita",
        preptime: "1h 25min",
        rating: "5 stars",
        image: "/dummydata/511728-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 6,
        title: "Pasta On The Border",
        preptime: "1h 25min",
        rating: "5 stars",
        image: "/dummydata/654857-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 7,
        title: "Pasta With Tuna",
        preptime: "1h 25min",
        rating: "5 stars",
        image: "/dummydata/654959-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 8,
        title: "Pasta Margherita",
        preptime: "1h 25min",
        rating: "5 stars",
        image: "/dummydata/511728-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 9,
        title: "Pasta On The Border",
        preptime: "1h 25min",
        rating: "5 stars",
        image: "/dummydata/654857-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 10,
        title: "Pasta With Tuna",
        preptime: "1h 25min",
        rating: "5 stars",
        image: "/dummydata/654959-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 11,
        title: "Pasta Margherita",
        preptime: "1h 25min",
        rating: "5 stars",
        image: "/dummydata/511728-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 12,
        title: "Pasta On The Border",
        preptime: "1h 25min",
        rating: "5 stars",
        image: "/dummydata/654857-312x231.jpg",
        imageType: "jpg",
      },
    ],
  };
}
